#!/usr/bin/env ruby

#
# Updates the Copyright year to current year (upon commit)
#
require 'date'
year = Date.today.strftime("%Y")

files= %x(git diff --cached --name-only)

# Change end-year to this year while preserving start year.
sed = "sed -i -e 's/Copyright (c) 2\\(...\\)-2... Microsemi Corporation/Copyright (c) 2\\1-#{year} Microsemi Corporation/g'"

files = files.split("\n")
files.each do |f|
  next if not File.exists? f
  system("#{sed} #{f}")
  system("git add #{f}")
end

system("clang-format -i -style=file vtss_appl/frr/*.hxx vtss_appl/frr/*.cxx")

exit 0
