# Steen Hegelund
# Time-Stamp: 2023-Jan-19 21:10

# Easier to see cursor
cursor:
  style:
    shape: Block
    blinking: Always
  blink_interval: 500

# Colors (Solarized Light)
colors:
  primary:
    background: '#fdf6e3' # base3
    foreground: '#657b83' # base00

  cursor:
    text:   '#fdf6e3' # base3
    cursor: '#657b83' # base00

  normal:
    black:   '#073642' # base02
    red:     '#dc322f' # red
    green:   '#859900' # green
    yellow:  '#b58900' # yellow
    blue:    '#268bd2' # blue
    magenta: '#d33682' # magenta
    cyan:    '#2aa198' # cyan
    white:   '#eee8d5' # base2

  bright:
    black:   '#002b36' # base03
    red:     '#cb4b16' # orange
    green:   '#586e75' # base01
    yellow:  '#657b83' # base00
    blue:    '#839496' # base0
    magenta: '#6c71c4' # violet
    cyan:    '#93a1a1' # base1
    white:   '#fdf6e3' # base3

font:
  size: 9.5
  normal:
    family: Inconsolata Nerd Font Mono
    style: Regular

  bold:
    family: Inconsolata Nerd Font Mono
    style: Bold

  italic:
    family: Inconsolata Nerd Font Mono
    style: Italic

  bold_italic:
    family: Inconsolata Nerd Font Mono
    style: Bold Italic

  offset:
    x: 0
    y: 1

window:
  padding:
    x: 6
    y: 6
  dynamic_title: true

bell:
  animation: Ease
  duration: 10
  color: '#cb4b16' # orange

window.opacity: 1.0

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"


key_bindings:
  # (Windows, Linux, and BSD only)
  - { key: V,              mods: Control|Shift,           action: Paste            }
  - { key: C,              mods: Control|Shift,           action: Copy             }
  - { key: Key0,           mods: Control,                 action: ResetFontSize    }
  - { key: PageUp,         mods: Control|Shift,           action: IncreaseFontSize }
  - { key: PageDown,       mods: Control|Shift,           action: DecreaseFontSize }

