# Regular Colors
TERM_BLUE_OR_YELLOW=$TERM_YELLOW

# Bold
TERM_BOLD_BLUE_OR_YELLOW=$TERM_BOLD_YELLOW

# Underline
TERM_ULINE_BLUE_OR_YELLOW=$TERM_ULINE_YELLOW

# Background
TERM_ON_BLUE_OR_YELLOW=$TERM_ON_YELLOW

# High Intensty
TERM_IBLUE_OR_IYELLOW=$TERM_IYELLOW

# Bold High Intensty
TERM_BIBLUE_OR_BIYELLOW=$TERM_BIYELLOW

# High Intensty backgrounds
TERM_ON_IBLUE_OR_IYELLOW=$TERM_ON_IYELLOW

TERM_DARK_BACKGROUND=1
