# Regular Colors
TERM_BLUE_OR_YELLOW=$TERM_BLUE

# Bold
TERM_BOLD_BLUE_OR_YELLOW=$TERM_BOLD_BLUE

# Underline
TERM_ULINE_BLUE_OR_YELLOW=$TERM_ULINE_BLUE

# Background
TERM_ON_BLUE_OR_YELLOW=$TERM_ON_BLUE

# High Intensty
TERM_IBLUE_OR_IYELLOW=$TERM_IBLUE

# Bold High Intensty
TERM_BIBLUE_OR_BIYELLOW=$TERM_BIBLUE

# High Intensty backgrounds
TERM_ON_IBLUE_OR_IYELLOW=$TERM_ON_IBLUE

