#GIT_PS1_SHOWDIRTYSTATE=1
#GIT_PS1_SHOWUNTRACKEDFILES=1

#GIT_PS1_SHOWUPSTREAM=auto
GIT_PS1_DESCRIBE_STYLE=branch
GIT_PS1_SHOWCOLORHINTS=1

if [[ $EUID -ne 0 ]]; then
    if [ -z $TERM_DARK_BACKGROUND ]
    then
        PS1="$TERM_RED\u$TERM_BLUE_OR_YELLOW@$TERM_CYAN\h $TERM_BLUE_OR_YELLOW\w $TERM_GREEN\$(__git_ps1 '(%s) ')$TERM_PURPLE\$ $TERM_COLOR_OFF"
    else
        PS1="$TERM_BOLD_RED\u$TERM_BOLD_BLUE_OR_YELLOW@$TERM_BOLD_CYAN\h $TERM_BOLD_BLUE_OR_YELLOW\w $TERM_BOLD_GREEN\$(__git_ps1 '(%s) ')$TERM_BOLD_PURPLE\$ $TERM_COLOR_OFF"
    fi
else
    if [ -z $TERM_DARK_BACKGROUND ]
    then
        PS1="$TERM_BLACK\u$TERM_BLUE_OR_YELLOW@$TERM_CYAN\h $TERM_BLUE_OR_YELLOW\w $TERM_GREEN\$(__git_ps1 '(%s) ')$TERM_PURPLE\$ $TERM_COLOR_OFF"
    else
        PS1="$TERM_BOLD_BLACK\u$TERM_BOLD_BLUE_OR_YELLOW@$TERM_BOLD_CYAN\h $TERM_BOLD_BLUE_OR_YELLOW\w $TERM_BOLD_GREEN\$(__git_ps1 '(%s) ')$TERM_BOLD_PURPLE\$ $TERM_COLOR_OFF"
    fi
fi
